
name: TABTestKit CI

on:
  workflow_dispatch: # This allows you to manually run the workflow from GitHub's web UI
  pull_request:
    branches: [ '*' ] # This means this workflow will run when any PR is created or any changes are pushed to a PR, on any branch

jobs:
  test_xcode12_ios_13_14:
    name: Run tests on Xcode 12 and iOS 13/14
    runs-on: macOS-latest
    strategy:
      fail-fast: false
      matrix:
        ios: [13.7, 14.2]

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set Xcode version to 12.2
        run: sudo xcode-select -switch /Applications/Xcode_12.2.app
      - name: Link to 13.7 Simulators
        if: matrix.ios == '13.7'
        run: |
              echo "Creating Runtimes folder if needed..."
              sudo mkdir -p /Library/Developer/CoreSimulator/Profiles/Runtimes
              echo "Creating symlink of the iOS 13.7 runtime..."
              sudo ln -s /Applications/Xcode_11.7.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime /Library/Developer/CoreSimulator/Profiles/Runtimes/iOS\ 13.7.simruntime
      - name: Build for testing on iOS ${{ matrix.os }}
        run: xcodebuild build-for-testing -workspace Example/TABTestKit.xcworkspace -scheme TABTestKit-Example -destination 'platform=iOS Simulator,name=iPhone 11,OS=${{ matrix.ios }}'
      - name: Test on iPhone 11 on iOS ${{ matrix.os }}
        run: xcodebuild test-without-building -workspace Example/TABTestKit.xcworkspace -scheme TABTestKit-Example -destination 'platform=iOS Simulator,name=iPhone 11,OS=${{ matrix.ios }}'
      - name: Archive tests results
        if: ${{ failure() }}
        uses: actions/upload-artifact@v2
        with:
          name: Test-TABTestKit-Xcode12.2-iOS-${{ matrix.ios }}.xcresult
          path: /Users/runner/Library/Developer/Xcode/DerivedData/*/Logs/Test/*.xcresult
          
  build_spm:
    name: Ensure Swift Package Manager builds
    runs-on: macOS-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - xcode: 11.7
            ios: 13.7
          - xcode: 12.2
            ios: 14.2 

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set Xcode version to ${{ matrix.xcode }}
        run: sudo xcode-select -switch /Applications/Xcode_${{ matrix.xcode }}.app
      - name: Build Swift Package Manager
        run: xcodebuild -workspace package.xcworkspace -scheme TABTestKit -destination 'platform=iOS Simulator,name=iPhone 11,OS=${{ matrix.ios }}'

  build_carthage:
    name: Ensure Carthage builds
    runs-on: macOS-latest
    strategy:
      fail-fast: false
      matrix:
        xcode: [11.7, 12.2]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set Xcode version to ${{ matrix.xcode }}
        run: sudo xcode-select -switch /Applications/Xcode_${{ matrix.xcode }}.app
      - name: Build Carthage for Xcode 11 
        if: matrix.xcode == '11.7'
        run: carthage build --archive
      - name: Build Carthage for Xcode 12
        if: matrix.xcode == '12.2'
        run: ./carthage.sh build --archive

  build_cocoapods:
    name: Ensure Cocoapods builds
    runs-on: macOS-latest
    strategy:
      fail-fast: false
      matrix:
        xcode: [11.7, 12.2]

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set Xcode version to ${{ matrix.xcode }}
        run: sudo xcode-select -switch /Applications/Xcode_${{ matrix.xcode }}.app
      - name: Build Cocoapods without allowing warnings
        if: matrix.xcode == '11.7'
        run: pod lib lint --verbosep
      - name: Build Cocoapods with allowing warning
        if: matrix.xcode == '12.2'
        run: pod lib lint --verbose --allow-warnings # Record needs to be fixed on Xcode 13 when will drop iOS 13
